CREATE TABLE SERVICE_AUTHENTICATION
(
SERVICEAUTH_ID int primary key,
SERVICEAUTH_USERNAME VARCHAR(50),
SERVICEAUTH_LOGIN VARCHAR(25),
SERVICEAUTH_PASSWORD VARCHAR(50) NOT NULL,
SERVICEAUTH_FORGOTPASSWORD VARCHAR(50),
SERVICEAUTH_RESETPASSWORD VARCHAR(50));

SELECT * FROM SERVICE_AUTHENTICATION;
insert into SERVICE_AUTHENTICATION values('Niya','niyu765','nj87','','');
insert into SERVICE_AUTHENTICATION values('Aditi','adi4765','','njhu7','njh7');
insert into SERVICE_AUTHENTICATION values(1,'Aditi','adi4765','','njhu7','njh7');
 
UPDATE TABLE SERVICE_AUTHENTICATION
ADD ID INT;
